services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # container:host. Map the container port 3000 to the host port 3000
    volumes:
      - .:/app # host:container. Mount the host directory ./ to the container directory /app
      - /app/node_modules # prevents the node_modules directory from being overwritten by the volume mount,
      # ensuring that the container uses its own installed dependencies instead of those in the host machine
    environment:
      - NODE_ENV=development # Enables hot-reloading, detailed error messages, and development-specific features
